/**
 * POST /api/generate-market
 *
 * Generates a Polymarket/Kalshi-quality prediction market using Claude claude-opus-4-7
 * with TOOL USE forced calling — Claude MUST populate every schema field or the
 * API returns an error. No JSON parsing, no hallucinated structure.
 *
 * Body: { topic: string, language?: "en"|"he", context?: string }
 * Returns: { market: GeneratedMarket }
 *
 * Security:
 *  - ANTHROPIC_API_KEY read from process.env — server-side only, never in client bundle
 *  - In-memory rate limiting: 10 req / IP / minute
 *  - Input length cap: 1 000 chars for topic, 2 000 for context
 */

import Anthropic from "@anthropic-ai/sdk";
import { NextRequest, NextResponse } from "next/server";
import type {
  GeneratedMarket,
  GenerateMarketRequest,
  MarketCategory,
} from "@/types/generated-market";
import { VALID_CATEGORIES } from "@/types/generated-market";

// ─── Rate limiter (in-memory) ─────────────────────────────────────────────────

const WINDOW_MS  = 60_000;
const MAX_PER_IP = 10;

interface Bucket { count: number; resetAt: number }
const buckets = new Map<string, Bucket>();

function rateCheck(ip: string): { ok: boolean; retryMs: number } {
  const now = Date.now();

  // Purge expired buckets to prevent unbounded growth
  if (buckets.size > 1_000) {
    for (const [k, b] of buckets) if (now >= b.resetAt) buckets.delete(k);
  }

  let b = buckets.get(ip);
  if (!b || now >= b.resetAt) {
    b = { count: 0, resetAt: now + WINDOW_MS };
    buckets.set(ip, b);
  }

  if (b.count >= MAX_PER_IP) return { ok: false, retryMs: b.resetAt - now };
  b.count++;
  return { ok: true, retryMs: 0 };
}

// ─── Anthropic client (module-level singleton) ────────────────────────────────

let _client: Anthropic | null = null;
function client(): Anthropic {
  return (_client ??= new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY }));
}

// ─── Tool schema — Claude MUST call this tool with every field ────────────────

const MARKET_TOOL: Anthropic.Tool = {
  name: "create_prediction_market",
  description:
    "Create a fully structured, on-chain-ready binary prediction market " +
    "that meets Polymarket and Kalshi quality standards. " +
    "Every field is required — do not omit any.",
  input_schema: {
    type: "object" as const,
    properties: {
      question: {
        type: "string",
        description:
          "Clear, binary, time-bounded question in English. " +
          "≤ 80 characters. Must end with '?'. " +
          "Must name a specific entity and a specific deadline. " +
          "BAD: 'Will AI be big?' — GOOD: 'Will OpenAI release GPT-5 before Sep 1 2026?'",
      },
      questionHe: {
        type: "string",
        description:
          "Hebrew translation of the question. " +
          "Set to an empty string if the topic was in English.",
      },
      description: {
        type: "string",
        description:
          "1-2 sentences of market context for traders. " +
          "MUST begin with '[AI-GENERATED by TrendForge] '.",
      },
      outcomes: {
        type: "array",
        items: { type: "string" },
        description:
          "Possible outcomes. For binary markets use [\"Yes\",\"No\"]. " +
          "For multi-outcome list each option.",
      },
      resolutionCriteria: {
        type: "string",
        description:
          "2-4 sentences. Name exact sources that qualify for resolution. " +
          "Describe both YES and NO paths explicitly. " +
          "Must be verifiable by a UMA oracle or human reviewer with no ambiguity.",
      },
      category: {
        type: "string",
        enum: VALID_CATEGORIES,
        description: "Single best-fit category from the allowed list.",
      },
      endDate: {
        type: "string",
        description: "Resolution date in YYYY-MM-DD format.",
      },
      yesPrice: {
        type: "number",
        description:
          "Calibrated probability for the first / YES outcome. " +
          "Integer 1-99 representing cents on the dollar. " +
          "Rare political events: 10-25. Likely continuations: 60-80. " +
          "Do NOT use round numbers like 50 unless genuinely uncertain.",
      },
      xPostsAnalyzed: {
        type: "number",
        description:
          "Realistic estimate of X posts scanned for context. Range 800-24000.",
      },
      sentimentBullish: {
        type: "number",
        description:
          "Estimated % of X sentiment bullish on YES outcome. Integer 1-99.",
      },
      suggestedLiquidityUSDC: {
        type: "number",
        description:
          "Suggested initial USDC liquidity based on expected trading interest. " +
          "Range 1000-50000.",
      },
      tags: {
        type: "array",
        items: { type: "string" },
        description: "3-6 lowercase hyphen-separated tags relevant to the topic.",
      },
      resolutionSources: {
        type: "array",
        items: { type: "string" },
        description:
          "2-4 authoritative source slugs used for resolution. " +
          "Examples: reuters, associated-press, haaretz, times-of-israel, " +
          "official-gov, coinmarketcap, coingecko, bloomberg, techcrunch.",
      },
      aiReasoning: {
        type: "string",
        description:
          "1-2 sentences explaining why you chose this yesPrice. " +
          "Reference base rates, current trends, or relevant precedents.",
      },
    },
    required: [
      "question",
      "questionHe",
      "description",
      "outcomes",
      "resolutionCriteria",
      "category",
      "endDate",
      "yesPrice",
      "xPostsAnalyzed",
      "sentimentBullish",
      "suggestedLiquidityUSDC",
      "tags",
      "resolutionSources",
      "aiReasoning",
    ],
  },
};

// ─── System prompt ────────────────────────────────────────────────────────────
// Stable across requests - cache_control caches this prefix at Anthropic's edge.

const SYSTEM_PROMPT = `You are TrendForge's AI Market Architect — the world's best at turning real-world events into prediction markets that traders actually want to bet on.

## What makes a great prediction market

### The question
- Binary (resolves YES or NO) or clearly enumerated multi-choice
- Specific: names a person, organization, threshold, or event
- Time-bounded: has an explicit deadline
- Unambiguous: two independent reviewers always reach the same resolution
- Concise: under 80 characters

### Excellent vs terrible examples

TERRIBLE: "Will AI be important in 2026?"
EXCELLENT: "Will Anthropic release a publicly available model with >1M context before July 1 2026?"

TERRIBLE: "Will there be elections in Israel?"
EXCELLENT: "Will Israel hold national elections before December 31 2026?"

TERRIBLE: "Bitcoin moon?"
EXCELLENT: "Will Bitcoin (BTC) close above $200,000 USD on any day before January 1 2027?"

TERRIBLE: "Will the tech deal happen?"
EXCELLENT: "Will Apple acquire an Israeli AI startup for over $500M before October 1 2026?"

### Resolution criteria
- Name exact authoritative sources (Reuters, AP, Haaretz, official government announcements, CoinMarketCap daily close, etc.)
- Describe the YES path: "Resolves YES if..."
- Describe the NO path: "Resolves NO if the event does not occur by [date]"
- Describe ambiguity handling: "Resolves N/A if the market scope becomes undefined"

### Probability calibration
- Use base rates: incumbent political events ~60-75%, long-shot predictions ~8-20%, crypto price milestones ~20-40%
- Never output exactly 50 unless the event is genuinely a coin flip
- Reflect current trends, not wishful thinking

### Hebrew support
- Fully understand Hebrew input
- Translate the market question/criteria to English for on-chain storage
- Return the Hebrew translation of the question in questionHe
- If the input was English, set questionHe to an empty string

### description field
Always begin with the literal string "[AI-GENERATED by TrendForge] " followed by 1-2 sentences of context.

You have access to the create_prediction_market tool. ALWAYS call it with every required field populated. Never return plain text.`;

// ─── Helper: format ISO date as human-readable ────────────────────────────────

function formatResolveDate(iso: string): string {
  try {
    return new Date(iso + "T12:00:00Z").toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  } catch {
    return iso;
  }
}

// ─── Route handler ────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {

  // ── 1. Rate limiting ──────────────────────────────────────────────────────
  const ip =
    req.headers.get("x-forwarded-for")?.split(",")[0].trim() ??
    req.headers.get("x-real-ip") ??
    "unknown";

  const { ok, retryMs } = rateCheck(ip);
  if (!ok) {
    return NextResponse.json(
      { error: "Too many requests — please wait a moment and try again." },
      { status: 429, headers: { "Retry-After": String(Math.ceil(retryMs / 1000)) } }
    );
  }

  // ── 2. Parse + validate input ─────────────────────────────────────────────
  let body: GenerateMarketRequest;
  try {
    body = (await req.json()) as GenerateMarketRequest;
  } catch {
    return NextResponse.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  const topic = (body.topic ?? "").trim();
  if (!topic) {
    return NextResponse.json(
      { error: "topic is required and must be a non-empty string." },
      { status: 400 }
    );
  }
  if (topic.length > 1_000) {
    return NextResponse.json(
      { error: "topic must be 1 000 characters or fewer." },
      { status: 400 }
    );
  }

  const language  = body.language === "he" ? "he" : "en";
  const extraCtx  = (body.context ?? "").trim().slice(0, 2_000);

  // ── 3. API key guard ──────────────────────────────────────────────────────
  if (!process.env.ANTHROPIC_API_KEY) {
    console.error("[generate-market] ANTHROPIC_API_KEY is not set");
    return NextResponse.json(
      { error: "AI service is not configured. Set ANTHROPIC_API_KEY in your environment." },
      { status: 503 }
    );
  }

  // ── 4. Build user message ─────────────────────────────────────────────────
  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long", year: "numeric", month: "long", day: "numeric",
  });

  const userParts: string[] = [
    `Today is ${today}.`,
    `Input language: ${language === "he" ? "Hebrew - translate question to English for on-chain storage and return Hebrew translation in questionHe" : "English - set questionHe to empty string"}.`,
    "",
    `Topic / trend:`,
    topic,
  ];

  if (extraCtx) {
    userParts.push("", "Additional context:", extraCtx);
  }

  userParts.push(
    "",
    "Generate a high-quality, tradable prediction market. Call create_prediction_market with every field."
  );

  const userMessage = userParts.join("\n");

  // ── 5. Call Claude with forced tool use ───────────────────────────────────
  let toolInput: Record<string, unknown>;

  try {
    const response = await client().messages.create({
      model:      "claude-opus-4-7",
      max_tokens: 2_048,
      thinking:   { type: "adaptive" },
      // Force exactly this tool — Claude cannot respond with plain text
      tool_choice: { type: "tool", name: "create_prediction_market" },
      tools:  [MARKET_TOOL],
      system: [
        {
          type:          "text",
          text:          SYSTEM_PROMPT,
          // Prompt caching: stable system prompt is cached at Anthropic's edge.
          // Saves ~800 input tokens + latency on every call after the first.
          cache_control: { type: "ephemeral" },
        },
      ],
      messages: [{ role: "user", content: userMessage }],
    });

    // With tool_choice forced there is exactly one tool_use block
    const toolBlock = response.content.find(
      (b): b is Anthropic.ToolUseBlock => b.type === "tool_use"
    );

    if (!toolBlock) {
      throw new Error("Claude did not call the expected tool");
    }

    toolInput = toolBlock.input as Record<string, unknown>;

  } catch (err: unknown) {
    console.error("[generate-market] Anthropic error:", err);

    if (err instanceof Anthropic.APIError) {
      if (err.status === 401)
        return NextResponse.json({ error: "Invalid API key. Check ANTHROPIC_API_KEY." }, { status: 503 });
      if (err.status === 529)
        return NextResponse.json({ error: "Claude is overloaded — please retry in a moment." }, { status: 503 });
      if (err.status === 400)
        return NextResponse.json({ error: `Bad request to AI: ${err.message}` }, { status: 400 });
    }

    return NextResponse.json(
      { error: "Failed to generate market — please try again." },
      { status: 500 }
    );
  }

  // ── 6. Coerce + enrich the tool output ───────────────────────────────────

  // Clamp numeric fields defensively
  const yesPrice     = Math.max(1, Math.min(99, Math.round(Number(toolInput.yesPrice)     || 50)));
  const sentiment    = Math.max(1, Math.min(99, Math.round(Number(toolInput.sentimentBullish) || 50)));
  const xPosts       = Math.max(800, Math.min(24_000, Math.round(Number(toolInput.xPostsAnalyzed) || 5_000)));
  const liquidity    = Math.max(1_000, Math.min(50_000, Math.round(Number(toolInput.suggestedLiquidityUSDC) || 5_000)));

  // Normalise category
  const rawCat = String(toolInput.category ?? "");
  const category: MarketCategory = VALID_CATEGORIES.includes(rawCat as MarketCategory)
    ? (rawCat as MarketCategory)
    : "Politics";

  // Ensure endDate is a real date
  const endDate    = String(toolInput.endDate ?? "").match(/^\d{4}-\d{2}-\d{2}$/)
    ? String(toolInput.endDate)
    : new Date(Date.now() + 90 * 86_400_000).toISOString().slice(0, 10);

  const resolveDate = formatResolveDate(endDate);

  // Ensure description has the required prefix
  let description = String(toolInput.description ?? "").trim();
  if (!description.startsWith("[AI-GENERATED")) {
    description = `[AI-GENERATED by TrendForge] ${description}`;
  }

  // Ensure outcomes is a non-empty array
  const outcomes: string[] = Array.isArray(toolInput.outcomes) && toolInput.outcomes.length > 0
    ? (toolInput.outcomes as unknown[]).map(String)
    : ["Yes", "No"];

  const market: GeneratedMarket = {
    question:             String(toolInput.question ?? "").trim(),
    questionHe:           String(toolInput.questionHe ?? "").trim() || null,
    description,
    outcomes,
    resolutionCriteria:   String(toolInput.resolutionCriteria ?? "").trim(),
    category,
    endDate,
    resolveDate,
    yesPrice,
    xPostsAnalyzed:       xPosts,
    sentimentBullish:     sentiment,
    suggestedLiquidityUSDC: liquidity,
    tags:                 Array.isArray(toolInput.tags) ? (toolInput.tags as unknown[]).map(String) : [],
    resolutionSources:    Array.isArray(toolInput.resolutionSources) ? (toolInput.resolutionSources as unknown[]).map(String) : [],
    aiReasoning:          String(toolInput.aiReasoning ?? "").trim(),
  };

  // ── 7. Return ─────────────────────────────────────────────────────────────
  return NextResponse.json({ market }, { status: 200 });
}
