/**
 * Shared types for TrendForge's AI-generated prediction markets.
 *
 * Used by:
 *  - app/api/generate-market/route.ts  (server — tool input schema)
 *  - app/(app)/ai-generator/page.tsx   (client — UI state)
 *  - hooks/useCreateMarket.ts          (client — on-chain publish)
 */

// Mirrors CATEGORY_OPTIONS in the AI Generator page
export type MarketCategory =
  | "Politics"
  | "Geopolitics"
  | "Crypto"
  | "Tech"
  | "Finance"
  | "Sports"
  | "Israel";

export const VALID_CATEGORIES: MarketCategory[] = [
  "Politics",
  "Geopolitics",
  "Crypto",
  "Tech",
  "Finance",
  "Sports",
  "Israel",
];

/**
 * The structured output Claude returns via tool_use.
 * Field names intentionally match the Polymarket / Kuest API contract
 * so they can be passed directly to useCreateMarket.create().
 */
export interface GeneratedMarket {
  /** Binary question, English, ≤ 80 chars, ends with "?" */
  question: string;

  /** Hebrew translation — null when input was English */
  questionHe: string | null;

  /** 1-2 sentence context. Starts with "[AI-GENERATED by TrendForge]" */
  description: string;

  /** Possible outcomes — binary: ["Yes","No"]; multi-choice: ["A","B","C"] */
  outcomes: string[];

  /** 2-4 sentences naming sources + YES/NO resolution paths */
  resolutionCriteria: string;

  category: MarketCategory;

  /** ISO date YYYY-MM-DD */
  endDate: string;

  /** Human-readable, e.g. "Oct 1, 2026" — derived server-side from endDate */
  resolveDate: string;

  /** Claude's probability for the first (YES/bullish) outcome — 1 to 99 */
  yesPrice: number;

  /** Realistic estimated X posts Claude scanned — 800 to 24 000 */
  xPostsAnalyzed: number;

  /** % of X sentiment bullish on the YES outcome — 1 to 99 */
  sentimentBullish: number;

  /** Suggested initial liquidity pool in USDC — 1 000 to 50 000 */
  suggestedLiquidityUSDC: number;

  /** 3-6 lowercase hyphen-separated tags */
  tags: string[];

  /** 2-4 authoritative resolution sources (lowercase slug) */
  resolutionSources: string[];

  /** 1-2 sentences explaining the probability calibration */
  aiReasoning: string;
}

// ─── API shapes ───────────────────────────────────────────────────────────────

export interface GenerateMarketRequest {
  topic: string;
  language?: "en" | "he";
  context?: string;
}

export interface GenerateMarketResponse {
  market: GeneratedMarket;
}

export interface GenerateMarketError {
  error: string;
}
