"use client";

/**
 * useCreateMarket - full on-chain market creation flow.
 *
 * Steps:
 *   1. Check USDC allowance for CTF contract (for initial liquidity split)
 *   2. Approve USDC if needed
 *   3. Call CTF.prepareCondition(oracle, questionId, 2)
 *   4. Wait for confirmation - get conditionId from logs
 *   5. (Optional) splitPosition to seed initial YES/NO liquidity
 *   6. Register market with CLOB API so it appears in order book
 *
 * The questionId is keccak256(abi.encodePacked(question, creator, salt))
 * This ensures each market is unique even with identical questions.
 *
 * AI metadata:
 *   We prefix the market description with "[AI-GENERATED by TrendForge]"
 *   This is stored on-chain in the CLOB market registration,
 *   making it queryable via the Gamma API.
 *
 * TODO: Future UMA resolution integration:
 *   After market close, the resolver calls:
 *     UMA.assertTruth(ancillaryData, bond, liveness, identifier)
 *   If unchallenged after `liveness` seconds, UMA calls:
 *     CTF.reportPayouts(questionId, payouts)  // [1e18, 0] for YES, [0, 1e18] for NO
 *   Users then call CTF.redeemPositions() to collect winnings.
 *
 * TODO: Fee collection:
 *   Kuest lets you set feeRecipient = your wallet in the CTF Exchange config.
 *   Each trade pays feeRateBps to feeRecipient automatically.
 *   Set NEXT_PUBLIC_FEE_RECIPIENT to your wallet address.
 */

import { useState, useCallback } from "react";
import {
  useWriteContract,
  useWaitForTransactionReceipt,
  useChainId,
  useSignTypedData,
} from "wagmi";
import {
  keccak256,
  encodePacked,
} from "viem";
import type { Address } from "viem";
import { CTF_ABI } from "@/lib/abis";
import { getAddresses, toUSDCUnits } from "@/lib/contracts";
import { registerMarketWithClob } from "@/lib/clob";
import { useUSDCApproval } from "./useApproval";

// ---- Types ------------------------------------------------------------------

export interface CreateMarketParams {
  question:           string;
  description:        string;    // Claude-generated description
  resolutionCriteria: string;    // Claude-generated resolution rules
  category:           string;
  endDate:            string;    // ISO date string
  aiGenerated:        boolean;
  initialLiquidityUSDC?: number; // optional seed liquidity
}

export type CreateMarketStep =
  | "idle"
  | "approving_usdc"
  | "creating_condition"
  | "waiting_condition"
  | "seeding_liquidity"
  | "registering_clob"
  | "complete"
  | "error";

export interface CreateMarketState {
  step:         CreateMarketStep;
  stepLabel:    string;
  progress:     number;          // 0-100
  conditionId:  string | null;
  questionId:   string | null;
  yesTokenId:   string | null;
  noTokenId:    string | null;
  txHash:       `0x${string}` | undefined;
  clobMarketId: string | null;
  error:        string | null;
  create:       (params: CreateMarketParams) => Promise<void>;
  reset:        () => void;
}

const STEP_LABELS: Record<CreateMarketStep, string> = {
  idle:               "Ready",
  approving_usdc:     "Approving USDC...",
  creating_condition: "Creating market condition on-chain...",
  waiting_condition:  "Waiting for Polygon confirmation...",
  seeding_liquidity:  "Seeding initial liquidity...",
  registering_clob:   "Registering with order book...",
  complete:           "Market is live!",
  error:              "Error",
};

const STEP_PROGRESS: Record<CreateMarketStep, number> = {
  idle:               0,
  approving_usdc:     15,
  creating_condition: 30,
  waiting_condition:  55,
  seeding_liquidity:  70,
  registering_clob:   85,
  complete:           100,
  error:              0,
};

// ---- Hook -------------------------------------------------------------------

export function useCreateMarket(creator: Address | undefined): CreateMarketState {
  const chainId   = useChainId();
  const contracts = getAddresses(chainId);

  const [step,         setStep]         = useState<CreateMarketStep>("idle");
  const [conditionId,  setConditionId]  = useState<string | null>(null);
  const [questionIdHex,setQuestionId]   = useState<string | null>(null);
  const [yesTokenId,   setYesTokenId]   = useState<string | null>(null);
  const [noTokenId,    setNoTokenId]    = useState<string | null>(null);
  const [clobMarketId, setClobMarketId] = useState<string | null>(null);
  const [error,        setError]        = useState<string | null>(null);

  // CTF prepareCondition transaction
  const {
    writeContractAsync: writeCtf,
    data: ctfTxHash,
    reset: resetCtfWrite,
  } = useWriteContract();

  // Wait for CTF transaction
  const { data: ctfReceipt } = useWaitForTransactionReceipt({
    hash: ctfTxHash,
  });

  // USDC approval for initial liquidity split
  const initialLiquidityUnits = toUSDCUnits(500); // default 500 USDC seed
  const approval = useUSDCApproval(creator, initialLiquidityUnits);

  // Optional: splitPosition for initial liquidity
  const { writeContractAsync: writeSplit } = useWriteContract();

  const create = useCallback(async (params: CreateMarketParams) => {
    if (!creator) {
      setError("Wallet not connected");
      return;
    }

    setError(null);

    try {
      // --- Step 0: Build questionId (unique bytes32 hash) ---
      //
      // The questionId must match what the UMA oracle will use for resolution.
      // For Kuest self-hosted: derive however you like, the oracle just needs
      // to know the same questionId when it calls reportPayouts().
      //
      // For Polymarket-compatible markets, the questionId is typically
      // keccak256 of the ancillaryData bytes that UMA uses.
      const salt     = BigInt(Date.now());
      const qId      = keccak256(
        encodePacked(
          ["string", "address", "uint256"],
          [params.question, creator, salt]
        )
      );
      setQuestionId(qId);

      // --- Step 1: USDC approval (if seeding liquidity) ---
      if (params.initialLiquidityUSDC && params.initialLiquidityUSDC > 0) {
        if (approval.needsApproval) {
          setStep("approving_usdc");
          approval.approve();
          // Wait for approval to complete
          await new Promise<void>((resolve, reject) => {
            const poll = setInterval(() => {
              if (approval.state === "approved") {
                clearInterval(poll);
                resolve();
              } else if (approval.state === "error") {
                clearInterval(poll);
                reject(new Error(approval.error ?? "Approval failed"));
              }
            }, 1000);
          });
        }
      }

      // --- Step 2: prepareCondition on CTF ---
      setStep("creating_condition");

      const aiPrefix = params.aiGenerated
        ? "[AI-GENERATED by TrendForge] "
        : "";

      // Full description includes AI prefix, description, and resolution criteria
      const _fullDescription = `${aiPrefix}${params.description}\n\nResolution: ${params.resolutionCriteria}`;

      // Use admin wallet as resolver so we can resolve markets manually.
      // The oracle address is the ONLY address allowed to call CTF.reportPayouts().
      const resolverAddress = (
        process.env.NEXT_PUBLIC_ADMIN_WALLET ?? contracts.ORACLE
      ) as Address;

      const txHash = await writeCtf({
        address:      contracts.CTF,
        abi:          CTF_ABI,
        functionName: "prepareCondition",
        args: [
          resolverAddress,  // admin wallet — can call reportPayouts to resolve
          qId,              // unique questionId
          2n,               // 2 outcome slots: YES (index 0) and NO (index 1)
        ],
      });

      // --- Step 3: wait for confirmation ---
      setStep("waiting_condition");

      // Derive conditionId (deterministic, matches what CTF contract emits)
      // conditionId = keccak256(abi.encodePacked(oracle, questionId, outcomeSlots))
      const cId = keccak256(
        encodePacked(["address", "bytes32", "uint256"], [resolverAddress, qId, 2n])
      );
      setConditionId(cId);

      // --- Step 4: optional initial liquidity split ---
      if (params.initialLiquidityUSDC && params.initialLiquidityUSDC > 0) {
        setStep("seeding_liquidity");

        const liquidityUnits = toUSDCUnits(params.initialLiquidityUSDC);

        await writeSplit({
          address:      contracts.CTF,
          abi:          CTF_ABI,
          functionName: "splitPosition",
          args: [
            contracts.USDC,
            "0x0000000000000000000000000000000000000000000000000000000000000000" as `0x${string}`,
            cId,
            [1n, 2n], // partition: [YES, NO]
            liquidityUnits,
          ],
        });

        // Wait a couple seconds for the split tx
        await new Promise(r => setTimeout(r, 2500));
      }

      // --- Step 5: derive token IDs and register with CLOB ---
      setStep("registering_clob");

      // Gnosis CTF position ID derivation (exact formula from the contract):
      //   collectionId = keccak256(encodePacked(conditionId, indexSet)) + parentCollectionId
      //   positionId   = keccak256(encodePacked(collateralToken, collectionId))
      //
      // parentCollectionId = 0 for root positions, so:
      //   collectionId = keccak256(encodePacked(conditionId, indexSet))
      //
      // indexSet 1 = YES (first slot), indexSet 2 = NO (second slot)
      const yesCollectionId = keccak256(
        encodePacked(["bytes32", "uint256"], [cId, 1n])
      );
      const noCollectionId = keccak256(
        encodePacked(["bytes32", "uint256"], [cId, 2n])
      );

      const yesTokenIdStr = BigInt(
        keccak256(encodePacked(["address", "bytes32"], [contracts.USDC, yesCollectionId]))
      ).toString();
      const noTokenIdStr = BigInt(
        keccak256(encodePacked(["address", "bytes32"], [contracts.USDC, noCollectionId]))
      ).toString();

      setYesTokenId(yesTokenIdStr);
      setNoTokenId(noTokenIdStr);

      const clobResult = await registerMarketWithClob(
        cId,
        qId,
        params.question,
        `${aiPrefix}${params.description}`,
        params.resolutionCriteria,
        params.endDate,
        yesTokenIdStr,
        noTokenIdStr,
      );

      if (!clobResult.success) {
        // CLOB registration failing is non-critical - market exists on-chain
        // The CLOB can be registered manually later
        console.warn("CLOB registration failed (non-critical):", clobResult.error);
      } else {
        setClobMarketId(clobResult.marketId ?? null);
      }

      setStep("complete");
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      setError(msg);
      setStep("error");
    }
  }, [creator, contracts, approval, writeCtf, writeSplit]);

  return {
    step,
    stepLabel: STEP_LABELS[step],
    progress:  STEP_PROGRESS[step],
    conditionId,
    questionId: questionIdHex,
    yesTokenId,
    noTokenId,
    txHash:     ctfTxHash,
    clobMarketId,
    error,
    create,
    reset: () => {
      setStep("idle");
      setConditionId(null);
      setQuestionId(null);
      setYesTokenId(null);
      setNoTokenId(null);
      setClobMarketId(null);
      setError(null);
      resetCtfWrite();
      approval.reset();
    },
  };
}
